apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: tasks
          image: shelltechsolutionsllc/movies-api:latest
          env:
            - name: auth.api.url
              value: http://auth-service:8080/api/v1/auth/