spring:
  application:
    name: movies

omdb:
  api:
    key: 80af670

auth:
  api:
    url: http://127.0.0.1:8080/api/v1/auth/ #WITHIN LOCAL ENVIRONMENT (INTELLIJ)
    #url: http://host.docker.internal:8080/api/v1/auth/ #WITHIN DOCKER CONTAINER


server:
  port : 8081